### ISSUE TITLE
SSL operation failed with code 5

### ISSUE THREAD

**Issue by LordFit** [iMD14/ServerSwitcher#1]
Error: file_get_contents(): SSL operation failed with code 5. OpenSSL Error messages: error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:80000002:system library::No such file or directory error:0A000086:SSL routines::certificate verify failed
File: plugins/ServerSwitcher-593fe09fb50f7707b3ac1aaded6a6863bb9c8bfc/src/Main
Line: 26
Type: ErrorException

Backtrace:
#0 (): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[361] file_get_contents(): SSL operation failed with code 5. OpenSSL Error messages:.e, string[91] /root/survival/plugins/ServerSwitcher-593fe09fb50f7707b3ac1aaded6a6863bb9c8bfc/s, int 26)
#1 plugins/ServerSwitcher/src/Main(26): file_get_contents(string[55] https://poggit.pmmp.io/plugins.json?name=ServerSwitcher)
#2 pmsrc/src/plugin/PluginBase(118): iMD14\ServerSwitcher\Main->onEnable()
#3 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#4 pmsrc/src/Server(1400): pocketmine\plugin\PluginManager->enablePlugin(object iMD14\ServerSwitcher\Main#50162)
#5 pmsrc/src/Server(1044): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#42045)
#6 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[15] /root/survival/, string[23] /root/survival/plugins/)
#7 pmsrc/src/PocketMine(357): pocketmine\server()
#8 pmsrc(11): require(string[59] phar:///root/survival/PocketMine-MP.phar/src/PocketMine.php)

**Comment by iMD14** [comment]
Im aware of that This should be fixed in next update
